# On every push this script is executed
name: Zola on GitHub Pages

on: 
 push:
  branches:
   - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.19.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Send Webmentions
      run: |
        npm install @remy/webmention
        npx webmention https://webmention.app/check?token=${{ secrets.WEBMENTION_APP_TOKEN }}&url=https://scientiac.space/atom.xml --limit=0 --send

